# Generated by Django 4.0.4 on 2022-06-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('sha256hash', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
        ),
    ]
